### ISSUE TITLE
Chore: Naming convention and formatting standardization - lich.rbw

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/lich-5#62]
Need to clean up naming conventions (perhaps adjusting namespace) and address formatting standardization in the lich.rbw file.

Zero functional change expected.

**Comment by mrhoribu** [comment]
Would like to standardize waitrt? and waitcastrt? to return true/false instead of an integer.

Currently:
```ruby
def checkrt
  [0, XMLData.roundtime_end.to_f - Time.now.to_f + XMLData.server_time_offset.to_f].max
end

def checkcastrt
  [0, XMLData.cast_roundtime_end.to_f - Time.now.to_f + XMLData.server_time_offset.to_f].max
end

def waitrt?
  sleep checkrt
end

def waitcastrt?
  sleep checkcastrt
end
```

Proposed (need likely better naming):
```ruby
def waitrt?
  current_rt = checkrt
  if current_rt.to_f > 0.0
    sleep(current_rt)
    return true
  else
    return false
  end
end

def waitcastrt?
  current_castrt = checkcastrt
  if current_castrt.to_f > 0.0
    sleep(current_rt)
    return true
  else
    return false
  end
end
```

This will allow current functionality to continue, but now return proper true/false as should be expected when using a `?` at the end of a function/method instead of the current returning of `0` that they do now if no RT.
